### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by zloi47** [andrewda/hltv-livescore#20]
Hello,

I am using 
`sb.on('scoreboard', function(data) {
    console.log(data);
});`

but not sure how to get Player, Team and Round class data.

Thanks in advance.

**Comment by mrwhale** [comment]
What is printed out when that callback is fired?

It should print an array of data. Included in there are player team and round details
example:

```
harry@dashboard:~$ nodejs score.js 
{ map: 'de_cache',
  bombPlanted: true,
  currentRound: 7,
  teams: 
   { '1': 
      { id: 6615,
        name: 'OpTic',
        score: 5,
        side: 1,
        players: [Object],
        history: [Object] },
     '2': 
      { id: 7010,
        name: 'Immortals',
        score: 1,
        side: 2,
        players: [Object],
        history: [Object] } } }
```
You can then dot reference the required data you want

For example, within the callback

```
console.log("Team Name " + data.teams[1].name)
console.log("Team Name " + data.teams[2].name)
//This will print
// Team Name Optic
// Team Name Immortals
//team array with always be 1, or 2
```

**Comment by andrewda** [comment]
Adding on to what @mrwhale said, you can also request the array of teams (including their respective players) using [`getTeams()`](https://github.com/andrewda/hltv-livescore#getteamscallback), and an array of players using [`getPlayers()`](https://github.com/andrewda/hltv-livescore#getplayerscallback)
