### ISSUE TITLE
Does hltv emit the bomb site the bomb has been planted at?

### ISSUE THREAD

**Issue by mrwhale** [andrewda/hltv-livescore#21]
Would be nice to know this (if its given by the scorebot)

**Comment by andrewda** [comment]
No, it does not. This would be an awesome addition, but until it appears on the HLTV Scorebot for games, it won't appear here.

**Comment by mrwhale** [comment]
Didnt think so :( thanks anyway! Awesome project by the way. I am currently building it into something for personal use, and its amazinly easy!

**Comment by andrewda** [comment]
Sweet, glad you like it! Open some issues if you have any suggestions to make it easier to use.
