### ISSUE TITLE
Add colour to player/team names for events to show which side they are currently on

### ISSUE THREAD

**Issue by mrwhale** [andrewda/hltv-livescore#22]
Be a nice addition to add natively (maybe an optional library?)

In the thing I am writing using this library I have also added `chalk` to add colour to output. Similar to the scorebot on the hltv site

example during a `kill` callback

```
if(data.victim.team.side == 1){
        T -= 1;
        console.log(chalk.blue(data.killer.name), 'killed', chalk.red(data.victim.name), 'with', data.weapon, data.headshot ? '(headshot)' : '', '(' + chalk.blue(CT) + ' vs ' + chalk.red(T) + ')');
    }else{
        CT -= 1;
        console.log(chalk.red(data.killer.name), 'killed', chalk.blue(data.victim.name), 'with', data.weapon, data.headshot ? '(headshot)' : '', '(' + chalk.blue(CT) + ' vs ' + chalk.red(T) + ')');
    }
```

It will then look like this in a commandline window 

![screenshot from 2016-09-19 12-47-38](https://cloud.githubusercontent.com/assets/7307429/18654048/80331f22-7f21-11e6-8a50-9d638a27fa9a.png)

**Comment by andrewda** [comment]
Good idea, but I don't want to add on to the dependency list more than necessary. This seems like it could be a good thing to put in the [wiki](https://github.com/andrewda/hltv-livescore/wiki) as a demo, but probably won't make it into the module.

**Comment by mrwhale** [comment]
Yeah fair call!

I'll be sure to add that in :)
