### ISSUE TITLE
Listening to multiple matches simultaneously

### ISSUE THREAD

**Issue by GitAngel** [andrewda/hltv-livescore#33]
Hi,

I've started using your module a few days ago and it works fine, except the situation when I need to get information for multiple matches simultaneously.  
I've been trying to create multiple instances of livescore and to pass an array of ids, but nothing of this works.  
Do you know if it's possible to listen to multiple matches?

**Comment by andrewda** [comment]
Huh, creating multiple instances should work fine. I'll look into this a bit more to see what the problem might be.

**Comment by GitAngel** [comment]
Thank you for your reply, Andrew.
When I create multiple instances, I receive data only from the last one.

Kind regards,
Dmytro TOLSTYI

2017-07-23 19:01 GMT+02:00 Andrew Dassonville <notifications@github.com>:

**Comment by andrewda** [comment]
@GitAngel I'll make a release in an hour or so with your changes. Thanks a bunch!

**Comment by GitAngel** [comment]
Thank you, @andrewda .
